### ISSUE TITLE
GPU Related Object Recognition Module Fatal Error

### ISSUE THREAD

**Issue by Shiul93** [mintforpeople/robobo-hri-vision#37]
`
com.mytechia.robobo.app E/AndroidRuntime: FATAL EXCEPTION: Thread-25
    Process: com.mytechia.robobo.app:robobo, PID: 21136
    java.lang.Error: FATAL EXCEPTION [Thread-25]
    Unity version     : 2019.3.15f1
    Device model      : HUAWEI PRA-LX1
    Device fingerprint: HUAWEI/PRA-LX1/HWPRA-H:7.0/HUAWEIPRA-LX1/C432B212:user/release-keys
    
    Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Following operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
    180 operations will run on the GPU, and the remaining 1 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
    Node number 181 (TfLiteGpuDelegateV2) 
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at com.mytechia.robobo.framework.hri.vision.objectRecognition.tensorFlow.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:294)
        at com.mytechia.robobo.framework.hri.vision.objectRecognition.tensorFlow.TensorFlowObjectRecognizerModule.onNewFrame(TensorFlowObjectRecognizerModule.java:188)
        at com.mytechia.robobo.framework.hri.vision.basicCamera.ACameraModule.notifyFrame(ACameraModule.java:52)
        at com.mytechia.robobo.framework.hri.vision.basicCamera.opencv.OpenCVCameraModule.onCameraFrame(OpenCVCameraModule.java:347)
        at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:392)
        at org.opencv.android.MyPortraitCameraView$CameraWorker.run(MyPortraitCameraView.java:364)
        at java.lang.Thread.run(Thread.java:776)
2021-02-15 13:23:16.661 21136-21275/com.mytechia.robobo.app I/Process: Sending signal. PID: 21136 SIG: 9

`

Might be related to #36

**Comment by Shiul93** [comment]
Fixed on a970060e1aec08f121539ca8c2319b1524b74cd6
