### ISSUE TITLE
Fatal Error Related to Aruco Detection

### ISSUE THREAD

**Issue by Shiul93** [mintforpeople/robobo-hri-vision#38]
App crashes randomly and returns to main menu

```2021-02-25 16:20:50.659 13281-13302/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: com.mytechia.robobo.app:robobo, PID: 13281
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2019.3.15f1 (59ff3e03856d)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'HUAWEI/POT-LX1EEA/HWPOT-H:9/HUAWEIPOT-L21/169C431R2:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    Timestamp: 2021-02-25 16:20:49+0100
    pid: 13281, tid: 13535, name: pool-7-thread-1  >>> com.mytechia.robobo.app:robobo <<<
    uid: 10232
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7b21a00000
        x0  00000000000001fe  x1  0000000000000002  x2  00000000ffffffff  x3  0000000000000001
        x4  0000007b219ff000  x5  0000000000000008  x6  0000008f00000108  x7  0000008f00000107
        x8  0000007b219fffe8  x9  00000000000001fd  x10 00000000000001fa  x11 0000007b219fffe8
        x12 00000000000001fd  x13 0000000000000000  x14 0000000000000000  x15 0000000000000008
        x16 0000007b2fd405e8  x17 0000007b2e7680a4  x18 0000007b25a0b488  x19 0000007b266597c8
        x20 0000007b26659820  x21 0000007b2665b588  x22 0000000000000106  x23 0000007b2275f97a
        x24 00000000000001e1  x25 0000007b2275fa81  x26 0000007b26659890  x27 fffffffffffffe1f
        x28 000000000000008d  x29 0000007b266597b0
        sp  0000007b26659770  lr  0000007b2ea19b3c  pc  0000007b2ea19cb8
    
    backtrace:
          #00 pc 0000000000694cb8  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #01 pc 0000000000695dbc  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (cvBoundingRect+248) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #02 pc 000000000057b7b4  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (cvFindNextContour+2152) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #03 pc 000000000057c8f0  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #04 pc 000000000057d8ac  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (cv::findContours(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)+984) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #05 pc 000000000057e2bc  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (cv::findContours(cv::_InputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)+108) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #06 pc 0000000000e3fb88  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #07 pc 0000000000453f88  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double)+208) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #08 pc 0000000000e30050  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (cv::aruco::detectMarkers(cv::_InputArray const&, cv::Ptr<cv::aruco::Dictionary> const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::Ptr<cv::aruco::DetectorParameters> const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&)+1828) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #09 pc 00000000002e4edc  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/base.apk (Java_org_opencv_aruco_Aruco_detectMarkers_10+184) (BuildId: 1b7d8e234030cb638838becf4f24740621d401a9)
          #10 pc 00000000000567f8  /data/app/com.mytechia.robobo.app-nVpNF3y8v7zg3EpOI0nJqQ==/oat/arm64/base.odex
    
        at base.0x694cb8(Native Method)
        at base.cvBoundingRect(cvBoundingRect:248)
        at base.cvFindNextContour(cvFindNextContour:2152)
        at base.0x57c8f0(Native Method)
        at base.cv::findContours(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)(findContours:984)
2021-02-25 16:20:50.659 13281-13302/? E/AndroidRuntime:     at base.cv::findContours(cv::_InputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)(findContours:108)
        at base.0xe3fb88(Native Method)
        at base.cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double)(parallel_for_:208)
        at base.cv::aruco::detectMarkers(cv::_InputArray const&, cv::Ptr<cv::aruco::Dictionary> const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::Ptr<cv::aruco::DetectorParameters> const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&)(detectMarkers:1828)
        at base.Java_org_opencv_aruco_Aruco_detectMarkers_10(Java_org_opencv_aruco_Aruco_detectMarkers_10:184)
        at base.0x567f8(Native Method)```

**Comment by Shiul93** [comment]
Expected to be fixed with 028bb0ed4fb5b413578466421e70549260b5e1fd
